{'ARSON': {},
 'ASSAULT': {'FIREARM': {'FELONY': {}, 'MISDEMEANOR': {}},
             'HANDS-FISTS-FEET': {'FELONY': {}, 'MISDEMEANOR': {}},
             'KNIFE': {'FELONY': {}, 'MISDEMEANOR': {}},
             'OTHER-SIMPLE': {'FELONY': {}, 'MISDEMEANOR': {}},
             'OTHER-WEAPON': {'FELONY': {}, 'MISDEMEANOR': {}},
             'PEACE-OFFICER': {'FELONY': {}, 'MISDEMEANOR': {}},
             'THREATS': {}},
 'COURT': {'CONTEMPT': {},
           'PROBATION': {},
           'WARRANT': {'FELONY': {}, 'MISDEMEANOR': {}}},
 'DOM-VIOL': {'BATTERY-SPOUSE': {},
              'COURT-ORDER': {},
              'DOMESTIC-DISPUTE': {},
              'PHONE': {}},
 'HOMICIDE': {},
 'LARCENY': {'BURGLARY': {'AUTO': {},
                          'COMMERCIAL': {},
                          'OTHER': {},
                          'RESIDENTIAL': {}},
             'FORGERY-COUNTERFEIT': {},
             'FRAUD': {},
             'THEFT': {'GRAND': {},
                       'PETTY': {},
                       'VEHICLE': {'AUTO': {},
                                   'CAR-JACKING': {},
                                   'OTHER': {},
                                   'TRUCK-BUS': {}}}},
 'MENTAL-ILLNESS': {},
 'OTHER': {'FOUND': {}, 'LOST': {}, 'MISSING-PERSON': {}},
 'QUALITY': {'CURFEW-LOITERING': {},
             'DISORDERLY-CONDUCT': {},
             'DRUG': {'POSSESSION': {'MARIJUANA': {},
                                     'NARCOTICS': {},
                                     'OTHER': {}},
                      'SALE-MFCTR': {'NARCOTICS': {}}},
             'LIQUOR': {}},
 'ROBBERY': {'FIREARM': {},
             'INHABITED-DWELLING': {},
             'KNIFE': {},
             'OTHER-WEAPON': {},
             'STRONG-ARM': {}},
 'SEX': {'OFFENDER': {}, 'OTHER': {}, 'PROSTITUTION': {}, 'RAPE': {}},
 'TRAFFIC': {'DUI': {}, 'HIT-RUN': {}, 'MISC': {}, 'TOWED-VEHICLE': {}},
 'VANDALISM': {},
 'WEAPONS': {}}
