# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 20:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OakCrime',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('opd_rd', models.CharField(db_index=True, max_length=10)),
                ('oidx', models.IntegerField()),
                ('cdateTime', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=500)),
                ('ctype', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('beat', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.CharField(blank=True, max_length=100, null=True)),
                ('xlng', models.FloatField(null=True)),
                ('ylat', models.FloatField(null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('ucr', models.CharField(blank=True, max_length=5, null=True)),
                ('statute', models.CharField(blank=True, max_length=50, null=True)),
                ('crimeCat', models.CharField(blank=True, max_length=50, null=True)),
                ('lastModDateTime', models.DateTimeField(auto_now=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('geobeat', models.CharField(blank=True, max_length=3, null=True)),
                ('ctractGeoID', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeType', models.CharField(max_length=20)),
                ('ylat', models.FloatField()),
                ('xlng', models.FloatField()),
                ('name', models.CharField(max_length=254)),
                ('desc', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Zip5Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statefp10', models.CharField(max_length=2)),
                ('zcta5ce10', models.CharField(max_length=5)),
                ('geoid10', models.CharField(max_length=7)),
                ('classfp10', models.CharField(max_length=2)),
                ('mtfcc10', models.CharField(max_length=5)),
                ('funcstat10', models.CharField(max_length=1)),
                ('aland10', models.FloatField()),
                ('awater10', models.FloatField()),
                ('intptlat10', models.CharField(max_length=11)),
                ('intptlon10', models.CharField(max_length=12)),
                ('partflg10', models.CharField(max_length=1)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
