# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyIncid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCat',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('ctypeDesc', models.CharField(db_index=True, max_length=100)),
                ('crimeCat', models.CharField(max_length=100)),
            ],
        ),
    ]
