# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyIncid', '0002_crimecat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oakcrime',
            name='crimeCat',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
