# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 23:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oakcrime',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
