# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_main', '0002_oakcrime_latlong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oakcrime',
            name='ctype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
